### ISSUE TITLE
コメントなども Slack に通知する

### ISSUE THREAD

**Issue by takano32** [arakawatomonori/covid19-surveyor#109]
![C0089384-2350-4A2A-9947-674CAD7E40B5](https://user-images.githubusercontent.com/16088/79639688-2d334b00-81c8-11ea-9e56-d6a54e362d52.jpeg)

**Comment by takano32** [comment]
たぶん、Slack の設定側。

![C1192DA8-7E6C-4850-900E-DAEBD1FF9FA6](https://user-images.githubusercontent.com/16088/79639779-ba769f80-81c8-11ea-8c67-5b1e65148288.jpeg)

**Comment by Nekoya3** [comment]
slack comment てすと

**Comment by Nekoya3** [comment]
対応完了のためclose
