### ISSUE TITLE
インデックスページの表示が遅い

### ISSUE THREAD

**Issue by yuiseki** [arakawatomonori/covid19-surveyor#129]
publish.shでindex.htmlを生成するのをやめて、index.htmlは普通にHTMLファイルとして置き、reduce.jsonのようなファイルをajaxで読み込んで表示するように変えたい

**Comment by Nekoya3** [comment]
:+1:

**Comment by chrome-cgi** [comment]
#124 はそういう趣旨で json 出力させてます

**Comment by yuiseki** [comment]
#124 をマージしたのでindex.jsonが存在する状態にはなった

**Comment by takano32** [comment]
インデックスページの表示が遅いのが問題だと思うのでタイトルを変えました。

タイトルの内容はそのまま起票の description に移動。

**Comment by takano32** [comment]
根本的な問題として、おそらくトピックの矩形がひとつでるたびに再計算が走る CSS となっているらしき挙動があるので、シンプルな方法でレンダリングすれば速くなりそう。

<img width="962" alt="スクリーンショット 2020-04-23 3 41 55" src="https://user-images.githubusercontent.com/16088/80021148-0f8e1a80-8515-11ea-8fe0-d53ee81c3417.png">

**Comment by yuiseki** [comment]
map-clientがトップページになったのでこのissueは閉じます

**Comment by takano32** [comment]
see also. #171
