### ISSUE TITLE
https://help.stopcovid19.jp/ のリンク表記の色が見やすい色にしたい

### ISSUE THREAD

**Issue by taisukef** [arakawatomonori/covid19-surveyor#145]

**Comment by Nekoya3** [comment]
詳細がほしいです。
どこのリンクを指しているのか等

**Comment by taisukef** [comment]
<img width="413" alt="helpstopcovid" src="https://user-images.githubusercontent.com/1715217/79976089-0d0cd000-84d7-11ea-8f6a-03c001bf1e0c.png">

> 関連の経済支援制度を「Code for Japan」のボランティア
このリンクなどです
もう少し明るい色にするとか、白でアンダーラインで見やすくなりそう

**Comment by Nekoya3** [comment]
![image](https://user-images.githubusercontent.com/17000370/79976154-20b83680-84d7-11ea-9a24-2f7523c95bd2.png)
変更案こちらです

**Comment by taisukef** [comment]
いいと思います！
