### ISSUE TITLE
Slackチャンネルを名前指定ではなく直接ID指定にする

### ISSUE THREAD

**Issue by MaySoMusician** [arakawatomonori/covid19-surveyor#152]
[こちら](https://qiita.com/YumaInaura/items/0c4f4adb33eb21032c08)の方法でチャンネルIDが取得できるので、 `.env` ではIDを指定しておけば

- `get_channels_id` の実行が不要
    https://github.com/arakawatomonori/covid19-surveyor/blob/26179e69d80ca0876ef33141a062ce3feb5d16b5/lib/slack-helper.sh#L7-L32
- チャンネル名変更が簡単になる

と思います。

**Comment by takano32** [comment]
可読性は低いですし、ボットなどの運用をするときはチャンネル名の変更が影響するのかを考えないことはないので閉じます。
