### ISSUE TITLE
https://help.stopcovid19.jp のjavascriptを修正したいが、コードが見つからない

### ISSUE THREAD

**Issue by shokai** [arakawatomonori/covid19-surveyor#153]
このリポジトリの中に https://help.stopcovid19.jp/ のwebサイトのソースコードが無い気がするのですが（あるのかもしれない）
どこにありますか？

**Comment by Nekoya3** [comment]
https://github.com/arakawatomonori/covid19-surveyor/blob/master/crawler/publish.sh

こちらになります

**Comment by shokai** [comment]
なるほど！ありがとうございます
