### ISSUE TITLE
.env がなくてローカルでmake publishできない

### ISSUE THREAD

**Issue by shokai** [arakawatomonori/covid19-surveyor#157]
READMEに従って実行していきました

    $ docker-compose up -d
    $ docker-compose exec crawler ./crawler/wget.sh data/test.csv
    $ ocker-compose exec crawler make publish

すると、Makefileで指定されている `.env` ファイルが見つからなくて、 `www-data/index.html` が生成できませんでした

[![Screenshot from Gyazo](https://gyazo.com/d9c0cb9057e81399814dbd6e7f4c4b4f/raw)](https://gyazo.com/d9c0cb9057e81399814dbd6e7f4c4b4f)

**Comment by shokai** [comment]
.env に何を書くべきなのかわかりませんが、とりあえずただ存在していれば良いみたいなので

    $ touch .env

したらpublishできました

**Comment by kobake** [comment]
ご報告＆暫定対処方法の共有ありがとうございます。

#241, #242, #243 で .env が無い場合に案内メッセージを出すように対応しました。

また、 .env についての説明ドキュメントを [Wiki](https://github.com/arakawatomonori/covid19-surveyor/wiki) に設置しました。

この Issue は解決済みということでクローズ致します。
