### ISSUE TITLE
インクリメンタル検索が重い

### ISSUE THREAD

**Issue by chrome-cgi** [arakawatomonori/covid19-surveyor#193]
件数と description の分量が増えてきたことでだいぶ重くなってる印象

**Comment by chrome-cgi** [comment]
気づいたけどこれ、どうやら検索が遅いというより、単純に500件超の要素を描くので遅くなってるっぽいな…？
特に外部リンクアイコンの有無でもだいぶ変わってくる

**Comment by takano32** [comment]
開発者ツールで見るかぎり、初期画面では `Layout`  にメチャクチャに時間がかかってました。

インクリメンタルサーチの計測もしたかったのですが、サンプルになる動作がよく分からず、保留しました。

`Layout` に時間がかからない CSS だと インクリメンタルサーチがどうなるのか、というのはちょっと気になりました。
