### ISSUE TITLE
回答すると楽しくなるような仕組みをつける：動物画像、ランキングやキリ番ツイートなど

### ISSUE THREAD

**Issue by yuiseki** [arakawatomonori/covid19-surveyor#31]

**Comment by takano32** [comment]
![ダウンロード](https://user-images.githubusercontent.com/16088/79342303-e810de00-7f67-11ea-9307-40796ae35b96.jpeg)

**Comment by takano32** [comment]
![IMG_1484](https://user-images.githubusercontent.com/16088/79342412-0ecf1480-7f68-11ea-9505-bab226da01c0.JPG)

**Comment by takano32** [comment]
マジレスをするとゲーミフィケーションを導入して回答者ランキングみたいなので争えるシステムにすると勝手に盛り上がると思う。

**Comment by yuiseki** [comment]
- 回答ボタンを押したときに「あなたは現在N件回答していて、全体でN位です」とお知らせする
- 回答数が100, 200, 300, ...などのキリ番のときには、ツイートできるリンクをつけて、貢献をアピールできるようにする

**Comment by takano32** [comment]
#141, #143, #144, #179 でランキングは実現済みなので閉じます。

別案は具体例を別に起票することにしましょう。
