### ISSUE TITLE
「厚生労働省」のページのときに${govname}表示が崩れる

### ISSUE THREAD

**Issue by MaySoMusician** [arakawatomonori/covid19-surveyor#39]
## 発生している問題
- 調査対象が厚生労働省のページのとき、 `${govname}が独自に実施しているものである` など `${govname}` を使用している場所で `govname = '厚生労働省\n厚生労働省'` となっている

![image](https://user-images.githubusercontent.com/34566290/79421008-f22cee00-7ff4-11ea-808d-cee563c0eaa2.png)

**Comment by yuiseki** [comment]
data/*をdomainでgrepしたときに複数マッチするとこうなるっぽい予感

**Comment by 515hikaru** [comment]
これ publish された HTML でも同じこと起きてますね。

![新型コロナウイルス（COVID-19）各自治体の経済支援制度まとめ](https://user-images.githubusercontent.com/34483340/79680972-8b0b7580-8250-11ea-918d-aed0002b9836.png)

**Comment by 515hikaru** [comment]
公開HP上は直ったようです。 https://help.stopcovid19.jp/

Slack の質問のほうは、現時点では検証が難しいですね。

**Comment by yuiseki** [comment]
一旦Closeします。問題あったらReopenしましょう。
