### ISSUE TITLE
PDFファイルの文字列も検索したい

### ISSUE THREAD

**Issue by yuiseki** [arakawatomonori/covid19-surveyor#5]
`grep -r コロナ --include="*.html" ./` ってやってしまっているので拡張子がhtmlじゃないとgrep対象にならない

**Comment by takano32** [comment]
strings コマンドを使うと良いのかも。

strings a.out

とかで、a.out から文字として取り出せるバイト列がビロビロ出てくる。

**Comment by 515hikaru** [comment]
この 「HTML 以外のファイル」って具体的にはどのようなものを対象にしているんでしょう？PDF はおそらく対象になりそうですが、 PDF 以外にありますか?

文書ファイル、というだけだとtest.csv のクロール結果をみる限り xlsx とか ppt とかもあったりするので、スコープ区切らないと収拾つかないなと。

**Comment by veilchen** [comment]
grep -aでバイナリファイルも対象になりますが、えらいことになりそうなので、少なくとも画像は除外したいですね…

**Comment by yuiseki** [comment]
とりあえずこのissueではPDFを対象とすることにしましょう

**Comment by 515hikaru** [comment]
Ubuntu には `pdftotext` とか `pdftohtml` とかのコマンドがあるようですね(`sudo apt install poppler-utils` とかではいる)。

試しにやってみました。PDF(https://www.cao.go.jp/others/kichou/covid_19/20200407.pdf) を `pdftotext` で変換すると、

```txt
令和２年４月７日
大臣官房企画調整課

新型コロナウイルス感染者について

内閣府職員について、本日７日（火）に新型コロナウイルスに感
染したことが確認されました。当該職員は既に入院して治療を開始
しております。
【概要】
年代：50代
性別：男性
居住地：東京都
勤務場所：中央合同庁舎第８号館

本件問合せ先：
内閣府大臣官房企画調整課
課
長
尾原 知明
課長補佐
中山 奈津美
電話：６２５７−１３９０(直通)
```

って感じになります。

改行とかもまんま反映されるので　"助\n成" とかになっていると grep にひっかからないかもしれませんが、とりあえず使えなくはないかと。

**Comment by veilchen** [comment]
一応www-data以下にある拡張子一覧置いておきます。
`find www-data/ -mindepth 2   -type f | sed -E 's#^.+/[^.]+\.?##' | sed -E 's#\?.*$##' | awk -F. '{print tolower($NF)}' | sort -f  | uniq ` して、明らかに変なもの(com%2flink%2f
 みたいなWordPress由来らしきもの)は手作業で除去しました。

> 
> 22
> 26
> action
> ai
> ashx
> asp
> aspx
> asx
> atom
> avi
> axd
> bes
> bmp
> bse
> cgi
> count
> css
> csv
> cur
> doc
> docx
> eot
> epub
> exe
> geojson
> gif
> htc
> htm
> html
> ico
> ics
> jpe
> jpeg
> jpg
> js
> json
> jsp
> jtd
> lzh
> mp3
> mp4
> pdf
> php
> phtml
> png
> ppt
> pptx
> psd
> rdf
> rss
> rtf
> shtm
> shtml
> svg
> swf
> thmx
> tif
> ttf
> txt
> wav
> webm
> webp
> wma
> wmv
> woff
> woff2
> xls
> xlsm
> xlsx
> xml
> zip
> 五f
> 遭f
> 愉g
> 搖漿

最後の方の文字化けは、[富山市の韓国語サイト](http://www.pref.toyama.jp/korean/index.html)由来のものみたいなので、気にしなくてよさそうです。

**Comment by takano32** [comment]
Poppler についてはこちらが詳しいです。

https://texwiki.texjp.org/?Poppler

```
$ brew install poppler
```

で macOS でも使えました。

**Comment by 515hikaru** [comment]
ちょっとこのタスク着手してみます。
