### ISSUE TITLE
index.htmlで説明文が長すぎるやつがいる問題

### ISSUE THREAD

**Issue by yuiseki** [arakawatomonori/covid19-surveyor#70]

**Comment by yuiseki** [comment]
案：200文字くらいでぶったぎってしまう

**Comment by chrome-cgi** [comment]
CSS で適当な高さを決めて隠しちゃうのはどうですか？
![help stopcovid19 jp_](https://user-images.githubusercontent.com/5283783/79579023-fc88de00-8101-11ea-89a5-fd0dc296bcca.png)

**Comment by yuiseki** [comment]
↑ナイスアイデア！！
