### ISSUE TITLE
都道府県、市区町村のドロップダウンで絞り込みしたい

### ISSUE THREAD

**Issue by yuiseki** [arakawatomonori/covid19-surveyor#71]

**Comment by Nekoya3** [comment]
titleからの絞り込みでよければすぐ実装できるかも？
取り込んでる都道府県、市区町村がわかれば行けそうな雰囲気

**Comment by yuiseki** [comment]
data/以下のディレクトリに都道府県、市区町村のCSVがあり、
名前,略称,URL
という形式になっています

**Comment by yuiseki** [comment]
地図で選択できるようになったのでこのissueは閉じます
