### ISSUE TITLE
make wget 等でディスク容量を使いすぎる問題に対応

### ISSUE THREAD

**Issue by kobake** [arakawatomonori/covid19-surveyor#86]
Slack #covid19-surveyor-dev
> chrome  1:13 PM, 2020-04-18
> make wget、50GBくらい容量食うと聞いてましたが、150GB以上空いてたSSDがいっぱいになって止まっちゃいましたね…
> 内容見ると謎の画像キャッシュみたいなので数GB食ってたりするので
> wget で画像をダウンロードしないとか、拡張子を制限すれば少し減りますかね

**Comment by kobake** [comment]
一旦対処療法で画像ファイル群を消します

```
cd /home/ubuntu/vscovid-crawler/www-data
find -name "*.png" | xargs rm -rf
find -name "*.jpg" | xargs rm -rf
```

**Comment by kobake** [comment]
勢いあまって必要なファイルも消しちゃったので復旧しました。

```
ubuntu@vscovid-crawler:~/vscovid-crawler$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        deleted:    www-data/android-chrome-192x192.png
        deleted:    www-data/android-chrome-256x256.png
        deleted:    www-data/apple-touch-icon.png
        deleted:    www-data/favicon-16x16.png
        deleted:    www-data/favicon-32x32.png
        deleted:    www-data/mstile-150x150.png
        deleted:    www-data/ogimg.png
```

↓ 対処

```
git checkout .
```

**Comment by kobake** [comment]
png と jpg の削除で 10GB 削減

```
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1       485G  224G  262G  47% /

↓

$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1       485G  214G  272G  44% /
```

**Comment by kobake** [comment]
gif も消します

**Comment by kobake** [comment]
拡張子が以下のファイルを手動削除することで 37GB ほどディスク使用量を削減できました。
png, jpg, jpeg, gif, mp4, mp3, zip, wmv, xls, xlsm, xlsx, xml, wav, webm, webp, wma

これらのファイルの扱いは後でスクリプトに組み込もうと思います。

**Comment by kobake** [comment]
doc, docx も追加。（これでさらに 1GB 削減）

**Comment by chrome-cgi** [comment]
大きいファイルを探して見てたらどうやら pdf がすごい容量食ってるようですね
何か間違ってなければ 150GBぐらいダウンロードしたうちの100GB超が pdf のようです…
```bash
$ find ./www-data/ -type f -name "*.pdf" -print0 | xargs -0 ls -al | awk '{COUNTER+=$5} END {print COUNTER}'
107033037377
```

**Comment by kobake** [comment]
PDF でかいですね…。消そうか迷いましたが、使う予定あるとのことで PDF は消さないでおきます。

## Slack ログ
https://cfj.slack.com/archives/C0120J2GPU1/p1587190767118200

> kobake  3:19 PM, 2020-04-18
> www-data 内の画像ファイル群を消しましたが10GB削減しか効果なかったです。
> mp4 を発掘したので、これも消します。
> pdf は、、、どうしましょうか。これも消しましょうかね・・・？

> yuiseki  3:19 PM, 2020-04-18
> いや！
> PDFはマイニングするという案があるのでまってください

> yuiseki  3:20 PM, 2020-04-18
> https://github.com/arakawatomonori/covid19-surveyor/issues/5
> これ

**Comment by kobake** [comment]
https://github.com/arakawatomonori/covid19-surveyor/pull/103
`make remove-large-files` で不要ファイルを削除できるようにしました。（マージ済み）

**Comment by kobake** [comment]
- make wget 時に remove-large-files を続けて実行 #108

これがマージされたら本 Issue をクローズしようと思います。
